{
    "statuses": [{
        "created_at": "Tue Mar 06 08:46:27 +0800 2012",
        "id": 3420502409961825,
        "mid": "3420502409961825",
        "idstr": "3420502409961825",
        "text": "中国烟草总公司与贵行有啥战略意义？",
        "source": "<a href=\"http://m.weibo.com/web/cellphone.php#ipad\" rel=\"nofollow\">iPad客户端</a>",
        "favorited": false,
        "truncated": false,
        "in_reply_to_status_id": "",
        "in_reply_to_user_id": "",
        "in_reply_to_screen_name": "",
        "geo": null,
        "user": {
            "id": 1813080181,
            "idstr": "1813080181",
            "screen_name": "薛蛮子",
            "name": "薛蛮子",
            "province": "11",
            "city": "5",
            "location": "北京 朝阳区",
            "description": "天使投资人薛蛮子 商业计划书请发信箱charlesxuesub@gmail.com",
            "url": "",
            "profile_image_url": "http://tp2.sinaimg.cn/1813080181/50/5615039894/1",
            "profile_url": "charlesxue",
            "domain": "charlesxue",
            "weihao": "",
            "gender": "m",
            "followers_count": 1978491,
            "friends_count": 1469,
            "statuses_count": 36575,
            "favourites_count": 827,
            "created_at": "Mon Sep 06 00:00:00 +0800 2010",
            "following": false,
            "allow_all_act_msg": true,
            "geo_enabled": true,
            "verified": true,
            "verified_type": 0,
            "remark": "",
            "allow_all_comment": true,
            "avatar_large": "http://tp2.sinaimg.cn/1813080181/180/5615039894/1",
            "verified_reason": "天使投资人、微博打拐发起人之一",
            "follow_me": false,
            "online_status": 1,
            "bi_followers_count": 1191,
            "lang": "zh-cn"
        },
        "retweeted_status": {
            "created_at": "Tue Mar 06 08:33:32 +0800 2012",
            "id": 3420499159685099,
            "mid": "3420499159685099",
            "idstr": "3420499159685099",
            "text": "【兴业银行“敲定”4家战投 募资263.8亿补血】兴业银行3月6日公告称，拟向中国人保资产管理股份有限公司、中国烟草总公司、北京市基础设施投资有限公司和上海正阳国际经贸有限公司等4家特定对象非公开发行A股股票。募资合计不超过263.80亿元，将全部用于补充公司核心资本。 http://t.cn/zOtnylv",
            "source": "<a href=\"http://weibo.com\" rel=\"nofollow\">新浪微博</a>",
            "favorited": false,
            "truncated": false,
            "in_reply_to_status_id": "",
            "in_reply_to_user_id": "",
            "in_reply_to_screen_name": "",
            "thumbnail_pic": "http://ww3.sinaimg.cn/thumbnail/66e4e3ddjw1dqps09vhatj.jpg",
            "bmiddle_pic": "http://ww3.sinaimg.cn/bmiddle/66e4e3ddjw1dqps09vhatj.jpg",
            "original_pic": "http://ww3.sinaimg.cn/large/66e4e3ddjw1dqps09vhatj.jpg",
            "geo": null,
            "user": {
                "id": 1726276573,
                "idstr": "1726276573",
                "screen_name": "ChinaVenture投中集团",
                "name": "ChinaVenture投中集团",
                "province": "11",
                "city": "5",
                "location": "北京 朝阳区",
                "description": "ChinaVenture投中集团是一家专注于中国投资市场的领先信息咨询机构。拥有中国VC/PE行业第一门户网站ChinaVenture投资中国网。",
                "url": "http://www.chinaventure.com.cn",
                "profile_image_url": "http://tp2.sinaimg.cn/1726276573/50/1280803344/1",
                "profile_url": "chinaventure",
                "domain": "chinaventure",
                "weihao": "",
                "gender": "m",
                "followers_count": 82342,
                "friends_count": 824,
                "statuses_count": 12033,
                "favourites_count": 9,
                "created_at": "Wed Apr 07 00:00:00 +0800 2010",
                "following": false,
                "allow_all_act_msg": true,
                "geo_enabled": true,
                "verified": true,
                "verified_type": 2,
                "remark": "",
                "allow_all_comment": true,
                "avatar_large": "http://tp2.sinaimg.cn/1726276573/180/1280803344/1",
                "verified_reason": "ChinaVenture投中集团官方微博",
                "follow_me": false,
                "online_status": 1,
                "bi_followers_count": 306,
                "lang": "zh-cn"
            },
            "reposts_count": 167,
            "comments_count": 41,
            "mlevel": 0,
            "visible": {
                "type": 0,
                "list_id": 0
            }
        },
        "reposts_count": 125,
        "comments_count": 91,
        "mlevel": 0,
        "visible": {
            "type": 0,
            "list_id": 0
        }
    },
    {
        "created_at": "Tue Mar 06 08:44:37 +0800 2012",
        "id": 3420501948584089,
        "mid": "3420501948584089",
        "idstr": "3420501948584089",
        "text": "支持减税",
        "source": "<a href=\"http://m.weibo.com/web/cellphone.php#ipad\" rel=\"nofollow\">iPad客户端</a>",
        "favorited": false,
        "truncated": false,
        "in_reply_to_status_id": "",
        "in_reply_to_user_id": "",
        "in_reply_to_screen_name": "",
        "geo": null,
        "user": {
            "id": 1813080181,
            "idstr": "1813080181",
            "screen_name": "薛蛮子",
            "name": "薛蛮子",
            "province": "11",
            "city": "5",
            "location": "北京 朝阳区",
            "description": "天使投资人薛蛮子 商业计划书请发信箱charlesxuesub@gmail.com",
            "url": "",
            "profile_image_url": "http://tp2.sinaimg.cn/1813080181/50/5615039894/1",
            "profile_url": "charlesxue",
            "domain": "charlesxue",
            "weihao": "",
            "gender": "m",
            "followers_count": 1978491,
            "friends_count": 1469,
            "statuses_count": 36575,
            "favourites_count": 827,
            "created_at": "Mon Sep 06 00:00:00 +0800 2010",
            "following": false,
            "allow_all_act_msg": true,
            "geo_enabled": true,
            "verified": true,
            "verified_type": 0,
            "remark": "",
            "allow_all_comment": true,
            "avatar_large": "http://tp2.sinaimg.cn/1813080181/180/5615039894/1",
            "verified_reason": "天使投资人、微博打拐发起人之一",
            "follow_me": false,
            "online_status": 1,
            "bi_followers_count": 1191,
            "lang": "zh-cn"
        },
        "retweeted_status": {
            "created_at": "Tue Mar 06 08:34:57 +0800 2012",
            "id": 3420499515866433,
            "mid": "3420499515866433",
            "idstr": "3420499515866433",
            "text": "【联想集团董事长：高增值税致国内商品比国外贵】3月4日，政协委员杨元庆在政协分组讨论会上炮轰高增值税。杨元庆称，现在不只是高档消费品国外比国内便宜，耐克鞋这些大众消费品也是如此，“联想电脑在国内没有办法卖得不贵，有17%增值税必须加到价格里面，产品毛利率只有15%。”http://t.cn/zOtRyIj",
            "source": "<a href=\"http://weibo.com\" rel=\"nofollow\">新浪微博</a>",
            "favorited": false,
            "truncated": false,
            "in_reply_to_status_id": "",
            "in_reply_to_user_id": "",
            "in_reply_to_screen_name": "",
            "geo": null,
            "user": {
                "id": 1618051664,
                "idstr": "1618051664",
                "screen_name": "头条新闻",
                "name": "头条新闻",
                "province": "11",
                "city": "8",
                "location": "北京 海淀区",
                "description": "播报每日全球各类重要资讯、突发新闻，全天24小时即时发布。欢迎报料、投稿，请发私信或者邮件：xlttnews@vip.sina.com",
                "url": "http://news.sina.com.cn/",
                "profile_image_url": "http://tp1.sinaimg.cn/1618051664/50/5621941467/0",
                "profile_url": "breakingnews",
                "domain": "breakingnews",
                "weihao": "",
                "gender": "f",
                "followers_count": 10174064,
                "friends_count": 83,
                "statuses_count": 42074,
                "favourites_count": 6,
                "created_at": "Fri Aug 28 00:00:00 +0800 2009",
                "following": false,
                "allow_all_act_msg": true,
                "geo_enabled": true,
                "verified": true,
                "verified_type": 3,
                "remark": "",
                "allow_all_comment": true,
                "avatar_large": "http://tp1.sinaimg.cn/1618051664/180/5621941467/0",
                "verified_reason": "新浪新闻中心24小时播报全球重大新闻",
                "follow_me": false,
                "online_status": 0,
                "bi_followers_count": 74,
                "lang": "zh-cn"
            },
            "reposts_count": 1255,
            "comments_count": 487,
            "mlevel": 0,
            "visible": {
                "type": 0,
                "list_id": 0
            }
        },
        "reposts_count": 343,
        "comments_count": 119,
        "mlevel": 0,
        "visible": {
            "type": 0,
            "list_id": 0
        }
    },
    {
        "created_at": "Tue Mar 06 08:44:00 +0800 2012",
        "id": 3420501793393411,
        "mid": "3420501793393411",
        "idstr": "3420501793393411",
        "text": "转发微博",
        "source": "<a href=\"http://m.weibo.com/web/cellphone.php#ipad\" rel=\"nofollow\">iPad客户端</a>",
        "favorited": false,
        "truncated": false,
        "in_reply_to_status_id": "",
        "in_reply_to_user_id": "",
        "in_reply_to_screen_name": "",
        "geo": null,
        "user": {
            "id": 1813080181,
            "idstr": "1813080181",
            "screen_name": "薛蛮子",
            "name": "薛蛮子",
            "province": "11",
            "city": "5",
            "location": "北京 朝阳区",
            "description": "天使投资人薛蛮子 商业计划书请发信箱charlesxuesub@gmail.com",
            "url": "",
            "profile_image_url": "http://tp2.sinaimg.cn/1813080181/50/5615039894/1",
            "profile_url": "charlesxue",
            "domain": "charlesxue",
            "weihao": "",
            "gender": "m",
            "followers_count": 1978491,
            "friends_count": 1469,
            "statuses_count": 36575,
            "favourites_count": 827,
            "created_at": "Mon Sep 06 00:00:00 +0800 2010",
            "following": false,
            "allow_all_act_msg": true,
            "geo_enabled": true,
            "verified": true,
            "verified_type": 0,
            "remark": "",
            "allow_all_comment": true,
            "avatar_large": "http://tp2.sinaimg.cn/1813080181/180/5615039894/1",
            "verified_reason": "天使投资人、微博打拐发起人之一",
            "follow_me": false,
            "online_status": 1,
            "bi_followers_count": 1191,
            "lang": "zh-cn"
        },
        "retweeted_status": {
            "created_at": "Tue Mar 06 08:34:58 +0800 2012",
            "id": 3420499515866445,
            "mid": "3420499515866445",
            "idstr": "3420499515866445",
            "text": "[怒][怒][怒][话筒][话筒][话筒]昨晩电视有此一幕：母亲响应学雷锋的号召，带孩子到孤儿院，说：去看看那里的孤儿有多么苦（大意）。孩子天真地回答母亲：他们也要毎天上学吧？！我一下子晕了，救救中国教育，救救我们的孩子吧！！！",
            "source": "<a href=\"http://m.weibo.com/web/cellphone.php#ipad\" rel=\"nofollow\">iPad客户端</a>",
            "favorited": false,
            "truncated": false,
            "in_reply_to_status_id": "",
            "in_reply_to_user_id": "",
            "in_reply_to_screen_name": "",
            "geo": null,
            "user": {
                "id": 1708643783,
                "idstr": "1708643783",
                "screen_name": "钱文忠",
                "name": "钱文忠",
                "province": "31",
                "city": "1000",
                "location": "上海",
                "description": "买书的，看书的，藏书的，教书的，偶尔也写书的",
                "url": "http://blog.sina.com.cn/qianwenzhong",
                "profile_image_url": "http://tp4.sinaimg.cn/1708643783/50/1283204663/1",
                "profile_url": "qianwenzhong1",
                "domain": "qianwenzhong1",
                "weihao": "",
                "gender": "m",
                "followers_count": 326015,
                "friends_count": 316,
                "statuses_count": 4751,
                "favourites_count": 366,
                "created_at": "Thu Mar 11 00:00:00 +0800 2010",
                "following": false,
                "allow_all_act_msg": false,
                "geo_enabled": false,
                "verified": true,
                "verified_type": 0,
                "remark": "",
                "allow_all_comment": false,
                "avatar_large": "http://tp4.sinaimg.cn/1708643783/180/1283204663/1",
                "verified_reason": "复旦大学历史学系教授",
                "follow_me": false,
                "online_status": 1,
                "bi_followers_count": 304,
                "lang": "zh-cn"
            },
            "reposts_count": 913,
            "comments_count": 3,
            "mlevel": 0,
            "visible": {
                "type": 0,
                "list_id": 0
            }
        },
        "reposts_count": 295,
        "comments_count": 90,
        "mlevel": 0,
        "visible": {
            "type": 0,
            "list_id": 0
        }
    },
    {
        "created_at": "Tue Mar 06 08:43:08 +0800 2012",
        "id": 3420501575287576,
        "mid": "3420501575287576",
        "idstr": "3420501575287576",
        "text": "转发微博",
        "source": "<a href=\"http://m.weibo.com/web/cellphone.php#ipad\" rel=\"nofollow\">iPad客户端</a>",
        "favorited": false,
        "truncated": false,
        "in_reply_to_status_id": "",
        "in_reply_to_user_id": "",
        "in_reply_to_screen_name": "",
        "geo": null,
        "user": {
            "id": 1813080181,
            "idstr": "1813080181",
            "screen_name": "薛蛮子",
            "name": "薛蛮子",
            "province": "11",
            "city": "5",
            "location": "北京 朝阳区",
            "description": "天使投资人薛蛮子 商业计划书请发信箱charlesxuesub@gmail.com",
            "url": "",
            "profile_image_url": "http://tp2.sinaimg.cn/1813080181/50/5615039894/1",
            "profile_url": "charlesxue",
            "domain": "charlesxue",
            "weihao": "",
            "gender": "m",
            "followers_count": 1978491,
            "friends_count": 1469,
            "statuses_count": 36575,
            "favourites_count": 827,
            "created_at": "Mon Sep 06 00:00:00 +0800 2010",
            "following": false,
            "allow_all_act_msg": true,
            "geo_enabled": true,
            "verified": true,
            "verified_type": 0,
            "remark": "",
            "allow_all_comment": true,
            "avatar_large": "http://tp2.sinaimg.cn/1813080181/180/5615039894/1",
            "verified_reason": "天使投资人、微博打拐发起人之一",
            "follow_me": false,
            "online_status": 1,
            "bi_followers_count": 1191,
            "lang": "zh-cn"
        },
        "retweeted_status": {
            "created_at": "Tue Mar 06 08:38:50 +0800 2012",
            "id": 3420500497797099,
            "mid": "3420500497797099",
            "idstr": "3420500497797099",
            "text": "政府收税，往往征收企业或个人百分之六七十的收入，非常“大气”。政府为老百姓办事，却经常显得非常“小气”。1993年提出教育经费占GDP 4%的目标，居然到今年才勉强实现。与日本、台湾等地相比，就是4%也太少了。这二十年教育投入不足，已经造成很多恶果。下一届政府能否狠狠心，提到10%？",
            "source": "<a href=\"http://weibo.com\" rel=\"nofollow\">新浪微博</a>",
            "favorited": false,
            "truncated": false,
            "in_reply_to_status_id": "",
            "in_reply_to_user_id": "",
            "in_reply_to_screen_name": "",
            "thumbnail_pic": "http://ww1.sinaimg.cn/thumbnail/537289f9jw1dqprzlujg9j.jpg",
            "bmiddle_pic": "http://ww1.sinaimg.cn/bmiddle/537289f9jw1dqprzlujg9j.jpg",
            "original_pic": "http://ww1.sinaimg.cn/large/537289f9jw1dqprzlujg9j.jpg",
            "geo": null,
            "user": {
                "id": 1400015353,
                "idstr": "1400015353",
                "screen_name": "贷帮尹飞",
                "name": "贷帮尹飞",
                "province": "44",
                "city": "3",
                "location": "广东 深圳",
                "description": "以小额信贷撬动乡村发展，欢迎脚踏实地的理想主义者“入伙”贷帮 daibang.com",
                "url": "http://blog.sina.com.cn/supervanka",
                "profile_image_url": "http://tp2.sinaimg.cn/1400015353/50/1280647902/0",
                "profile_url": "daybang",
                "domain": "daybang",
                "weihao": "",
                "gender": "f",
                "followers_count": 11137,
                "friends_count": 285,
                "statuses_count": 3213,
                "favourites_count": 464,
                "created_at": "Fri May 14 00:00:00 +0800 2010",
                "following": false,
                "allow_all_act_msg": false,
                "geo_enabled": true,
                "verified": true,
                "verified_type": 0,
                "remark": "",
                "allow_all_comment": true,
                "avatar_large": "http://tp2.sinaimg.cn/1400015353/180/1280647902/0",
                "verified_reason": "贷帮乡村发展计划创始人、秘书长",
                "follow_me": false,
                "online_status": 1,
                "bi_followers_count": 235,
                "lang": "zh-cn"
            },
            "reposts_count": 520,
            "comments_count": 85,
            "mlevel": 0,
            "visible": {
                "type": 0,
                "list_id": 0
            }
        },
        "reposts_count": 396,
        "comments_count": 126,
        "mlevel": 0,
        "visible": {
            "type": 0,
            "list_id": 0
        }
    },
    {
        "created_at": "Tue Mar 06 08:32:38 +0800 2012",
        "id": 3420498932853324,
        "mid": "3420498932853324",
        "idstr": "3420498932853324",
        "text": " //@开心的dcoolboy: //@徐小平: 所以只有政治体制改革才能救中国。//@萧山博士: 改革在其他领域都能大显神通，一旦延伸到政治领域，马上就寸步难行，最后总会爆发突然事件，使改革者措手不及，全军溃败。@薛蛮子@任志强@潘",
        "source": "<a href=\"http://m.weibo.com/web/cellphone.php#ipad\" rel=\"nofollow\">iPad客户端</a>",
        "favorited": false,
        "truncated": false,
        "in_reply_to_status_id": "",
        "in_reply_to_user_id": "",
        "in_reply_to_screen_name": "",
        "geo": null,
        "user": {
            "id": 1813080181,
            "idstr": "1813080181",
            "screen_name": "薛蛮子",
            "name": "薛蛮子",
            "province": "11",
            "city": "5",
            "location": "北京 朝阳区",
            "description": "天使投资人薛蛮子 商业计划书请发信箱charlesxuesub@gmail.com",
            "url": "",
            "profile_image_url": "http://tp2.sinaimg.cn/1813080181/50/5615039894/1",
            "profile_url": "charlesxue",
            "domain": "charlesxue",
            "weihao": "",
            "gender": "m",
            "followers_count": 1978491,
            "friends_count": 1469,
            "statuses_count": 36575,
            "favourites_count": 827,
            "created_at": "Mon Sep 06 00:00:00 +0800 2010",
            "following": false,
            "allow_all_act_msg": true,
            "geo_enabled": true,
            "verified": true,
            "verified_type": 0,
            "remark": "",
            "allow_all_comment": true,
            "avatar_large": "http://tp2.sinaimg.cn/1813080181/180/5615039894/1",
            "verified_reason": "天使投资人、微博打拐发起人之一",
            "follow_me": false,
            "online_status": 1,
            "bi_followers_count": 1191,
            "lang": "zh-cn"
        },
        "retweeted_status": {
            "created_at": "Mon Mar 05 18:45:39 +0800 2012",
            "id": 3420290820422357,
            "mid": "3420290820422357",
            "idstr": "3420290820422357",
            "text": "国防大学政委刘亚洲中将：中国传统政治奠基于商鞅，粗成于秦始皇，大成于汉武帝。独尊儒术就是独尊皇权。正因为这种背景，使得百多年来中国多次借鉴西方的政治改革都半途而废。改革在其他领域都能大显神通，一旦延伸到政治领域，马上就寸步难行，最后总会爆发突然事件，使改革者措手不及，全军溃败。",
            "source": "<a href=\"http://weibo.com\" rel=\"nofollow\">新浪微博</a>",
            "favorited": false,
            "truncated": false,
            "in_reply_to_status_id": "",
            "in_reply_to_user_id": "",
            "in_reply_to_screen_name": "",
            "thumbnail_pic": "http://ww1.sinaimg.cn/thumbnail/3daa9cf0jw1dqp42xyr1aj.jpg",
            "bmiddle_pic": "http://ww1.sinaimg.cn/bmiddle/3daa9cf0jw1dqp42xyr1aj.jpg",
            "original_pic": "http://ww1.sinaimg.cn/large/3daa9cf0jw1dqp42xyr1aj.jpg",
            "geo": null,
            "user": {
                "id": 1034591472,
                "idstr": "1034591472",
                "screen_name": "萧山博士",
                "name": "萧山博士",
                "province": "51",
                "city": "1",
                "location": "四川 成都",
                "description": "想哭就哭,想笑就笑,笑和哭都能带来前所未有的放松感。",
                "url": "",
                "profile_image_url": "http://tp1.sinaimg.cn/1034591472/50/5605609615/1",
                "profile_url": "xiaozejun",
                "domain": "xiaozejun",
                "weihao": "",
                "gender": "m",
                "followers_count": 30718,
                "friends_count": 1997,
                "statuses_count": 22479,
                "favourites_count": 8,
                "created_at": "Fri Sep 04 00:00:00 +0800 2009",
                "following": false,
                "allow_all_act_msg": true,
                "geo_enabled": false,
                "verified": true,
                "verified_type": 0,
                "remark": "",
                "allow_all_comment": true,
                "avatar_large": "http://tp1.sinaimg.cn/1034591472/180/5605609615/1",
                "verified_reason": "成都某核能研究院研究员",
                "follow_me": false,
                "online_status": 1,
                "bi_followers_count": 1731,
                "lang": "zh-cn"
            },
            "reposts_count": 1307,
            "comments_count": 268,
            "mlevel": 0,
            "visible": {
                "type": 0,
                "list_id": 0
            }
        },
        "reposts_count": 346,
        "comments_count": 115,
        "mlevel": 0,
        "visible": {
            "type": 0,
            "list_id": 0
        }
    },
    {
        "created_at": "Tue Mar 06 08:19:42 +0800 2012",
        "id": 3420495678719244,
        "mid": "3420495678719244",
        "idstr": "3420495678719244",
        "text": "续朱先生的话：许多人虽天天在“卑劣意识”中过活，却永不能发“男性的抗议”，只知怨天尤人，甚至于自己不长进，希望旁人也跟着他不长进，看旁人长进，只怀满肚子醋意。这种人是由知耻回到无耻辱，注定地要堕落到十八层地狱，永不超生。",
        "source": "<a href=\"http://m.weibo.com/web/cellphone.php#ipad\" rel=\"nofollow\">iPad客户端</a>",
        "favorited": false,
        "truncated": false,
        "in_reply_to_status_id": "",
        "in_reply_to_user_id": "",
        "in_reply_to_screen_name": "",
        "geo": null,
        "user": {
            "id": 1813080181,
            "idstr": "1813080181",
            "screen_name": "薛蛮子",
            "name": "薛蛮子",
            "province": "11",
            "city": "5",
            "location": "北京 朝阳区",
            "description": "天使投资人薛蛮子 商业计划书请发信箱charlesxuesub@gmail.com",
            "url": "",
            "profile_image_url": "http://tp2.sinaimg.cn/1813080181/50/5615039894/1",
            "profile_url": "charlesxue",
            "domain": "charlesxue",
            "weihao": "",
            "gender": "m",
            "followers_count": 1978491,
            "friends_count": 1469,
            "statuses_count": 36575,
            "favourites_count": 827,
            "created_at": "Mon Sep 06 00:00:00 +0800 2010",
            "following": false,
            "allow_all_act_msg": true,
            "geo_enabled": true,
            "verified": true,
            "verified_type": 0,
            "remark": "",
            "allow_all_comment": true,
            "avatar_large": "http://tp2.sinaimg.cn/1813080181/180/5615039894/1",
            "verified_reason": "天使投资人、微博打拐发起人之一",
            "follow_me": false,
            "online_status": 1,
            "bi_followers_count": 1191,
            "lang": "zh-cn"
        },
        "retweeted_status": {
            "created_at": "Tue Mar 06 08:18:15 +0800 2012",
            "id": 3420495313936578,
            "mid": "3420495313936578",
            "idstr": "3420495313936578",
            "text": "#紀念朱光潛先生#人自觉有缺陷，就起“卑劣意识”，自耻不如人，于是心中就起一种“男性的抗议”，自己说我也是人，我不该不如人，我必用我的意志力来弥补天然的缺陷。“男性的抗议”就是认清了一条路径上抵抗力最大而仍然勇往直前，百折不挠。—朱先生所作《朝抵抗力最大的路径走》http://t.cn/heulKu",
            "source": "<a href=\"http://m.weibo.com/web/cellphone.php#ipad\" rel=\"nofollow\">iPad客户端</a>",
            "favorited": false,
            "truncated": false,
            "in_reply_to_status_id": "",
            "in_reply_to_user_id": "",
            "in_reply_to_screen_name": "",
            "thumbnail_pic": "http://ww4.sinaimg.cn/thumbnail/6c116875jw1dqprkl2vfkj.jpg",
            "bmiddle_pic": "http://ww4.sinaimg.cn/bmiddle/6c116875jw1dqprkl2vfkj.jpg",
            "original_pic": "http://ww4.sinaimg.cn/large/6c116875jw1dqprkl2vfkj.jpg",
            "geo": null,
            "user": {
                "id": 1813080181,
                "idstr": "1813080181",
                "screen_name": "薛蛮子",
                "name": "薛蛮子",
                "province": "11",
                "city": "5",
                "location": "北京 朝阳区",
                "description": "天使投资人薛蛮子 商业计划书请发信箱charlesxuesub@gmail.com",
                "url": "",
                "profile_image_url": "http://tp2.sinaimg.cn/1813080181/50/5615039894/1",
                "profile_url": "charlesxue",
                "domain": "charlesxue",
                "weihao": "",
                "gender": "m",
                "followers_count": 1978491,
                "friends_count": 1469,
                "statuses_count": 36575,
                "favourites_count": 827,
                "created_at": "Mon Sep 06 00:00:00 +0800 2010",
                "following": false,
                "allow_all_act_msg": true,
                "geo_enabled": true,
                "verified": true,
                "verified_type": 0,
                "remark": "",
                "allow_all_comment": true,
                "avatar_large": "http://tp2.sinaimg.cn/1813080181/180/5615039894/1",
                "verified_reason": "天使投资人、微博打拐发起人之一",
                "follow_me": false,
                "online_status": 1,
                "bi_followers_count": 1191,
                "lang": "zh-cn"
            },
            "reposts_count": 384,
            "comments_count": 34,
            "mlevel": 0,
            "visible": {
                "type": 0,
                "list_id": 0
            }
        },
        "reposts_count": 231,
        "comments_count": 58,
        "mlevel": 0,
        "visible": {
            "type": 0,
            "list_id": 0
        }
    },
    {
        "created_at": "Tue Mar 06 08:18:15 +0800 2012",
        "id": 3420495313936578,
        "mid": "3420495313936578",
        "idstr": "3420495313936578",
        "text": "#紀念朱光潛先生#人自觉有缺陷，就起“卑劣意识”，自耻不如人，于是心中就起一种“男性的抗议”，自己说我也是人，我不该不如人，我必用我的意志力来弥补天然的缺陷。“男性的抗议”就是认清了一条路径上抵抗力最大而仍然勇往直前，百折不挠。—朱先生所作《朝抵抗力最大的路径走》http://t.cn/heulKu",
        "source": "<a href=\"http://m.weibo.com/web/cellphone.php#ipad\" rel=\"nofollow\">iPad客户端</a>",
        "favorited": false,
        "truncated": false,
        "in_reply_to_status_id": "",
        "in_reply_to_user_id": "",
        "in_reply_to_screen_name": "",
        "thumbnail_pic": "http://ww4.sinaimg.cn/thumbnail/6c116875jw1dqprkl2vfkj.jpg",
        "bmiddle_pic": "http://ww4.sinaimg.cn/bmiddle/6c116875jw1dqprkl2vfkj.jpg",
        "original_pic": "http://ww4.sinaimg.cn/large/6c116875jw1dqprkl2vfkj.jpg",
        "geo": null,
        "user": {
            "id": 1813080181,
            "idstr": "1813080181",
            "screen_name": "薛蛮子",
            "name": "薛蛮子",
            "province": "11",
            "city": "5",
            "location": "北京 朝阳区",
            "description": "天使投资人薛蛮子 商业计划书请发信箱charlesxuesub@gmail.com",
            "url": "",
            "profile_image_url": "http://tp2.sinaimg.cn/1813080181/50/5615039894/1",
            "profile_url": "charlesxue",
            "domain": "charlesxue",
            "weihao": "",
            "gender": "m",
            "followers_count": 1978491,
            "friends_count": 1469,
            "statuses_count": 36575,
            "favourites_count": 827,
            "created_at": "Mon Sep 06 00:00:00 +0800 2010",
            "following": false,
            "allow_all_act_msg": true,
            "geo_enabled": true,
            "verified": true,
            "verified_type": 0,
            "remark": "",
            "allow_all_comment": true,
            "avatar_large": "http://tp2.sinaimg.cn/1813080181/180/5615039894/1",
            "verified_reason": "天使投资人、微博打拐发起人之一",
            "follow_me": false,
            "online_status": 1,
            "bi_followers_count": 1191,
            "lang": "zh-cn"
        },
        "reposts_count": 384,
        "comments_count": 34,
        "mlevel": 0,
        "visible": {
            "type": 0,
            "list_id": 0
        }
    },
    {
        "created_at": "Tue Mar 06 08:01:09 +0800 2012",
        "id": 3420491010675981,
        "mid": "3420491010675981",
        "idstr": "3420491010675981",
        "text": "#纪念朱光潜先生#人之所以为人，就在能不为最大的抵抗力所压服。世间大多数人仍是惰性大于意志力，抵抗力稍大就要缴械投降。这种人在事实上失去最高生命的特征，堕落到无生命的物质的水平线上，和死尸一样东推东倒西推西倒。他们在道德学问事功各方面都决不会有成就，万一以庸庸得厚福，也是叨天之幸。",
        "source": "<a href=\"http://m.weibo.com/web/cellphone.php#ipad\" rel=\"nofollow\">iPad客户端</a>",
        "favorited": false,
        "truncated": false,
        "in_reply_to_status_id": "",
        "in_reply_to_user_id": "",
        "in_reply_to_screen_name": "",
        "thumbnail_pic": "http://ww2.sinaimg.cn/thumbnail/6c116875jw1dqpr2smlvsj.jpg",
        "bmiddle_pic": "http://ww2.sinaimg.cn/bmiddle/6c116875jw1dqpr2smlvsj.jpg",
        "original_pic": "http://ww2.sinaimg.cn/large/6c116875jw1dqpr2smlvsj.jpg",
        "geo": null,
        "user": {
            "id": 1813080181,
            "idstr": "1813080181",
            "screen_name": "薛蛮子",
            "name": "薛蛮子",
            "province": "11",
            "city": "5",
            "location": "北京 朝阳区",
            "description": "天使投资人薛蛮子 商业计划书请发信箱charlesxuesub@gmail.com",
            "url": "",
            "profile_image_url": "http://tp2.sinaimg.cn/1813080181/50/5615039894/1",
            "profile_url": "charlesxue",
            "domain": "charlesxue",
            "weihao": "",
            "gender": "m",
            "followers_count": 1978491,
            "friends_count": 1469,
            "statuses_count": 36575,
            "favourites_count": 827,
            "created_at": "Mon Sep 06 00:00:00 +0800 2010",
            "following": false,
            "allow_all_act_msg": true,
            "geo_enabled": true,
            "verified": true,
            "verified_type": 0,
            "remark": "",
            "allow_all_comment": true,
            "avatar_large": "http://tp2.sinaimg.cn/1813080181/180/5615039894/1",
            "verified_reason": "天使投资人、微博打拐发起人之一",
            "follow_me": false,
            "online_status": 1,
            "bi_followers_count": 1191,
            "lang": "zh-cn"
        },
        "reposts_count": 531,
        "comments_count": 98,
        "mlevel": 0,
        "visible": {
            "type": 0,
            "list_id": 0
        }
    },
    {
        "created_at": "Tue Mar 06 07:59:47 +0800 2012",
        "id": 3420490666161441,
        "mid": "3420490666161441",
        "idstr": "3420490666161441",
        "text": "转发微博",
        "source": "<a href=\"http://m.weibo.com/web/cellphone.php#ipad\" rel=\"nofollow\">iPad客户端</a>",
        "favorited": false,
        "truncated": false,
        "in_reply_to_status_id": "",
        "in_reply_to_user_id": "",
        "in_reply_to_screen_name": "",
        "geo": null,
        "user": {
            "id": 1813080181,
            "idstr": "1813080181",
            "screen_name": "薛蛮子",
            "name": "薛蛮子",
            "province": "11",
            "city": "5",
            "location": "北京 朝阳区",
            "description": "天使投资人薛蛮子 商业计划书请发信箱charlesxuesub@gmail.com",
            "url": "",
            "profile_image_url": "http://tp2.sinaimg.cn/1813080181/50/5615039894/1",
            "profile_url": "charlesxue",
            "domain": "charlesxue",
            "weihao": "",
            "gender": "m",
            "followers_count": 1978491,
            "friends_count": 1469,
            "statuses_count": 36575,
            "favourites_count": 827,
            "created_at": "Mon Sep 06 00:00:00 +0800 2010",
            "following": false,
            "allow_all_act_msg": true,
            "geo_enabled": true,
            "verified": true,
            "verified_type": 0,
            "remark": "",
            "allow_all_comment": true,
            "avatar_large": "http://tp2.sinaimg.cn/1813080181/180/5615039894/1",
            "verified_reason": "天使投资人、微博打拐发起人之一",
            "follow_me": false,
            "online_status": 1,
            "bi_followers_count": 1191,
            "lang": "zh-cn"
        },
        "retweeted_status": {
            "created_at": "Mon Mar 05 23:39:39 +0800 2012",
            "id": 3420364803719336,
            "mid": "3420364803719336",
            "idstr": "3420364803719336",
            "text": "【小小律师浦志强被迫告别微博】由于在天津开会，没带电脑，刚借到一台电脑发消息。下午浦大律给我发来手机短信，说他在新浪搜狐腾讯的微博全被删除，并被勒令不许接受外媒采访，让我代发消息向各位博友告别。抱歉，刚刚代发出。",
            "source": "<a href=\"http://weibo.com\" rel=\"nofollow\">新浪微博</a>",
            "favorited": false,
            "truncated": false,
            "in_reply_to_status_id": "",
            "in_reply_to_user_id": "",
            "in_reply_to_screen_name": "",
            "geo": null,
            "user": {
                "id": 1446475417,
                "idstr": "1446475417",
                "screen_name": "冬眠熊2010",
                "name": "冬眠熊2010",
                "province": "11",
                "city": "1000",
                "location": "北京",
                "description": "",
                "url": "",
                "profile_image_url": "http://tp2.sinaimg.cn/1446475417/50/1291350639/1",
                "profile_url": "u/1446475417",
                "domain": "",
                "weihao": "",
                "gender": "m",
                "followers_count": 71804,
                "friends_count": 1426,
                "statuses_count": 9999,
                "favourites_count": 5829,
                "created_at": "Fri Nov 26 00:00:00 +0800 2010",
                "following": false,
                "allow_all_act_msg": false,
                "geo_enabled": false,
                "verified": true,
                "verified_type": 0,
                "remark": "",
                "allow_all_comment": true,
                "avatar_large": "http://tp2.sinaimg.cn/1446475417/180/1291350639/1",
                "verified_reason": "天下公言文化传媒研究员李伟东 《中国改革》杂志社原社长",
                "follow_me": false,
                "online_status": 1,
                "bi_followers_count": 1346,
                "lang": "zh-cn"
            },
            "reposts_count": 1464,
            "comments_count": 375,
            "mlevel": 0,
            "visible": {
                "type": 0,
                "list_id": 0
            }
        },
        "reposts_count": 599,
        "comments_count": 223,
        "mlevel": 0,
        "visible": {
            "type": 0,
            "list_id": 0
        }
    },
    {
        "created_at": "Tue Mar 06 07:59:30 +0800 2012",
        "id": 3420490590327122,
        "mid": "3420490590327122",
        "idstr": "3420490590327122",
        "text": " //@太商公: 哈哈，老冯 //@任志强:哈哈。说的形象又实在。整个就是个强奸犯啊？ //@王巍w:摸着了就娇！ //@汪潮涌: 摸疼了就叫！//@何振红:介个冯仑，总是那么生动、深刻！",
        "source": "<a href=\"http://m.weibo.com/web/cellphone.php#ipad\" rel=\"nofollow\">iPad客户端</a>",
        "favorited": false,
        "truncated": false,
        "in_reply_to_status_id": "",
        "in_reply_to_user_id": "",
        "in_reply_to_screen_name": "",
        "geo": null,
        "user": {
            "id": 1813080181,
            "idstr": "1813080181",
            "screen_name": "薛蛮子",
            "name": "薛蛮子",
            "province": "11",
            "city": "5",
            "location": "北京 朝阳区",
            "description": "天使投资人薛蛮子 商业计划书请发信箱charlesxuesub@gmail.com",
            "url": "",
            "profile_image_url": "http://tp2.sinaimg.cn/1813080181/50/5615039894/1",
            "profile_url": "charlesxue",
            "domain": "charlesxue",
            "weihao": "",
            "gender": "m",
            "followers_count": 1978491,
            "friends_count": 1469,
            "statuses_count": 36575,
            "favourites_count": 827,
            "created_at": "Mon Sep 06 00:00:00 +0800 2010",
            "following": false,
            "allow_all_act_msg": true,
            "geo_enabled": true,
            "verified": true,
            "verified_type": 0,
            "remark": "",
            "allow_all_comment": true,
            "avatar_large": "http://tp2.sinaimg.cn/1813080181/180/5615039894/1",
            "verified_reason": "天使投资人、微博打拐发起人之一",
            "follow_me": false,
            "online_status": 1,
            "bi_followers_count": 1191,
            "lang": "zh-cn"
        },
        "retweeted_status": {
            "created_at": "Fri Mar 02 15:43:30 +0800 2012",
            "id": 3419157813313891,
            "mid": "3419157813313891",
            "idstr": "3419157813313891",
            "text": "【冯仑：政府的手老在我怀里乱摸】万通地产董事长冯仑近日用隐晦的比喻称政府的“手”伸得有点长。他说，有人说中国企业家为啥最近老讲体制的问题？因为政府的手老在我怀里乱摸，不能不说，又不能乱说。我在美国或台湾地区做房子，不用管市长说了啥，他的手也不会摸我，所以我也不用说他啥！",
            "source": "<a href=\"http://media.weibo.com\" rel=\"nofollow\">媒体版微博</a>",
            "favorited": false,
            "truncated": false,
            "in_reply_to_status_id": "",
            "in_reply_to_user_id": "",
            "in_reply_to_screen_name": "",
            "thumbnail_pic": "http://ww2.sinaimg.cn/thumbnail/4726cd59jw1dqlhydoj3yj.jpg",
            "bmiddle_pic": "http://ww2.sinaimg.cn/bmiddle/4726cd59jw1dqlhydoj3yj.jpg",
            "original_pic": "http://ww2.sinaimg.cn/large/4726cd59jw1dqlhydoj3yj.jpg",
            "geo": null,
            "user": {
                "id": 1193725273,
                "idstr": "1193725273",
                "screen_name": "中国企业家杂志",
                "name": "中国企业家杂志",
                "province": "11",
                "city": "1000",
                "location": "北京",
                "description": "一本立于商业领袖的领袖商业杂志  <br />\n   <br />\n我们的历史  <br />\n创刊于1985年，中国主流商业财经杂志公认的领导者。  <br />\n   <br />\n我…",
                "url": "http://www.iceo.com.cn/",
                "profile_image_url": "http://tp2.sinaimg.cn/1193725273/50/5611329118/1",
                "profile_url": "cne",
                "domain": "cne",
                "weihao": "",
                "gender": "m",
                "followers_count": 1415748,
                "friends_count": 489,
                "statuses_count": 12681,
                "favourites_count": 36,
                "created_at": "Fri Aug 28 00:00:00 +0800 2009",
                "following": false,
                "allow_all_act_msg": true,
                "geo_enabled": true,
                "verified": true,
                "verified_type": 3,
                "remark": "",
                "allow_all_comment": true,
                "avatar_large": "http://tp2.sinaimg.cn/1193725273/180/5611329118/1",
                "verified_reason": "《中国企业家》杂志官方微博",
                "follow_me": false,
                "online_status": 1,
                "bi_followers_count": 297,
                "lang": "zh-cn"
            },
            "reposts_count": 4161,
            "comments_count": 1041,
            "mlevel": 0,
            "visible": {
                "type": 0,
                "list_id": 0
            }
        },
        "reposts_count": 621,
        "comments_count": 161,
        "mlevel": 0,
        "visible": {
            "type": 0,
            "list_id": 0
        }
    },
    {
        "created_at": "Tue Mar 06 07:56:47 +0800 2012",
        "id": 3420489910846638,
        "mid": "3420489910846638",
        "idstr": "3420489910846638",
        "text": "强烈支持！",
        "source": "<a href=\"http://m.weibo.com/web/cellphone.php#ipad\" rel=\"nofollow\">iPad客户端</a>",
        "favorited": false,
        "truncated": false,
        "in_reply_to_status_id": "",
        "in_reply_to_user_id": "",
        "in_reply_to_screen_name": "",
        "geo": null,
        "user": {
            "id": 1813080181,
            "idstr": "1813080181",
            "screen_name": "薛蛮子",
            "name": "薛蛮子",
            "province": "11",
            "city": "5",
            "location": "北京 朝阳区",
            "description": "天使投资人薛蛮子 商业计划书请发信箱charlesxuesub@gmail.com",
            "url": "",
            "profile_image_url": "http://tp2.sinaimg.cn/1813080181/50/5615039894/1",
            "profile_url": "charlesxue",
            "domain": "charlesxue",
            "weihao": "",
            "gender": "m",
            "followers_count": 1978491,
            "friends_count": 1469,
            "statuses_count": 36575,
            "favourites_count": 827,
            "created_at": "Mon Sep 06 00:00:00 +0800 2010",
            "following": false,
            "allow_all_act_msg": true,
            "geo_enabled": true,
            "verified": true,
            "verified_type": 0,
            "remark": "",
            "allow_all_comment": true,
            "avatar_large": "http://tp2.sinaimg.cn/1813080181/180/5615039894/1",
            "verified_reason": "天使投资人、微博打拐发起人之一",
            "follow_me": false,
            "online_status": 1,
            "bi_followers_count": 1191,
            "lang": "zh-cn"
        },
        "retweeted_status": {
            "created_at": "Sun Mar 04 15:54:02 +0800 2012",
            "id": 3419885247915634,
            "mid": "3419885247915634",
            "idstr": "3419885247915634",
            "text": "我喜欢这个提案：崔永元：“我要为历史上的“反动电影”平反！” http://t.cn/zO5H50U",
            "source": "<a href=\"http://weibo.com\" rel=\"nofollow\">新浪微博</a>",
            "favorited": false,
            "truncated": false,
            "in_reply_to_status_id": "",
            "in_reply_to_user_id": "",
            "in_reply_to_screen_name": "",
            "geo": null,
            "user": {
                "id": 1039302717,
                "idstr": "1039302717",
                "screen_name": "色色猴",
                "name": "色色猴",
                "province": "11",
                "city": "8",
                "location": "北京 海淀区",
                "description": "1、围脖纯属私人空间个人行为自承其责，与所属国家民族地区行业或供职单位无任何关系。2、一言不合，拉黑不商量。||工邮：houzh@funshion.com",
                "url": "http://blog.sina.com.cn/sesehou",
                "profile_image_url": "http://tp2.sinaimg.cn/1039302717/50/1298121918/1",
                "profile_url": "sesehou",
                "domain": "sesehou",
                "weihao": "",
                "gender": "m",
                "followers_count": 47302,
                "friends_count": 1890,
                "statuses_count": 6003,
                "favourites_count": 283,
                "created_at": "Tue Jan 05 00:00:00 +0800 2010",
                "following": false,
                "allow_all_act_msg": true,
                "geo_enabled": true,
                "verified": true,
                "verified_type": 0,
                "remark": "",
                "allow_all_comment": true,
                "avatar_large": "http://tp2.sinaimg.cn/1039302717/180/1298121918/1",
                "verified_reason": "风行网原创中心和BD总监",
                "follow_me": false,
                "online_status": 0,
                "bi_followers_count": 1553,
                "lang": "zh-cn"
            },
            "reposts_count": 1395,
            "comments_count": 270,
            "mlevel": 0,
            "visible": {
                "type": 0,
                "list_id": 0
            }
        },
        "reposts_count": 508,
        "comments_count": 147,
        "mlevel": 0,
        "visible": {
            "type": 0,
            "list_id": 0
        }
    },
    {
        "created_at": "Tue Mar 06 07:55:44 +0800 2012",
        "id": 3420489646940702,
        "mid": "3420489646940702",
        "idstr": "3420489646940702",
        "text": "求专家科普@玮有我丁  //@沈东军: 爱吃辣的女性要注意了。 //@linalina1101: 爱吃辣不停灌冰可乐的人飘过。",
        "source": "<a href=\"http://m.weibo.com/web/cellphone.php#ipad\" rel=\"nofollow\">iPad客户端</a>",
        "favorited": false,
        "truncated": false,
        "in_reply_to_status_id": "",
        "in_reply_to_user_id": "",
        "in_reply_to_screen_name": "",
        "geo": null,
        "user": {
            "id": 1813080181,
            "idstr": "1813080181",
            "screen_name": "薛蛮子",
            "name": "薛蛮子",
            "province": "11",
            "city": "5",
            "location": "北京 朝阳区",
            "description": "天使投资人薛蛮子 商业计划书请发信箱charlesxuesub@gmail.com",
            "url": "",
            "profile_image_url": "http://tp2.sinaimg.cn/1813080181/50/5615039894/1",
            "profile_url": "charlesxue",
            "domain": "charlesxue",
            "weihao": "",
            "gender": "m",
            "followers_count": 1978491,
            "friends_count": 1469,
            "statuses_count": 36575,
            "favourites_count": 827,
            "created_at": "Mon Sep 06 00:00:00 +0800 2010",
            "following": false,
            "allow_all_act_msg": true,
            "geo_enabled": true,
            "verified": true,
            "verified_type": 0,
            "remark": "",
            "allow_all_comment": true,
            "avatar_large": "http://tp2.sinaimg.cn/1813080181/180/5615039894/1",
            "verified_reason": "天使投资人、微博打拐发起人之一",
            "follow_me": false,
            "online_status": 1,
            "bi_followers_count": 1191,
            "lang": "zh-cn"
        },
        "retweeted_status": {
            "created_at": "Mon Mar 05 10:05:50 +0800 2012",
            "id": 3420159995371318,
            "mid": "3420159995371318",
            "idstr": "3420159995371318",
            "text": "【女性长期吃辣，喝冰饮，容易患上妇科肿瘤】 吃辣时不停地灌冰水危害更大，冰水下肚，血液马上就会淤积在肠道和盆腔里，易致痛经、月经紊乱，子宫还会缩小、变硬，极易形成多囊卵巢和卵巢囊肿、腺肌症等妇科肿瘤，大大提高不孕的几率。重的是，盆腔淤血引起的不孕，做B超、妇科检查等发现不了。",
            "source": "<a href=\"http://weibo.com\" rel=\"nofollow\">新浪微博</a>",
            "favorited": false,
            "truncated": false,
            "in_reply_to_status_id": "",
            "in_reply_to_user_id": "",
            "in_reply_to_screen_name": "",
            "thumbnail_pic": "http://ww1.sinaimg.cn/thumbnail/91907363jw1dqop25y6m4j.jpg",
            "bmiddle_pic": "http://ww1.sinaimg.cn/bmiddle/91907363jw1dqop25y6m4j.jpg",
            "original_pic": "http://ww1.sinaimg.cn/large/91907363jw1dqop25y6m4j.jpg",
            "geo": null,
            "user": {
                "id": 2442163043,
                "idstr": "2442163043",
                "screen_name": "生活窍门大百科",
                "name": "生活窍门大百科",
                "province": "11",
                "city": "1000",
                "location": "北京",
                "description": "分享生活中的：趣味知识、实用窍门、生活百科！生活的、实用的、贴心的、小窍门、小贴士、小智慧！一个自由、免费、开放的百科全书！",
                "url": "",
                "profile_image_url": "http://tp4.sinaimg.cn/2442163043/50/5624939885/0",
                "profile_url": "u/2442163043",
                "domain": "",
                "weihao": "",
                "gender": "f",
                "followers_count": 19028,
                "friends_count": 33,
                "statuses_count": 98,
                "favourites_count": 0,
                "created_at": "Thu Nov 03 00:00:00 +0800 2011",
                "following": false,
                "allow_all_act_msg": false,
                "geo_enabled": true,
                "verified": false,
                "verified_type": -1,
                "remark": "",
                "allow_all_comment": true,
                "avatar_large": "http://tp4.sinaimg.cn/2442163043/180/5624939885/0",
                "verified_reason": "",
                "follow_me": false,
                "online_status": 1,
                "bi_followers_count": 0,
                "lang": "zh-cn"
            },
            "reposts_count": 2543,
            "comments_count": 192,
            "mlevel": 0,
            "visible": {
                "type": 0,
                "list_id": 0
            }
        },
        "reposts_count": 521,
        "comments_count": 104,
        "mlevel": 0,
        "visible": {
            "type": 0,
            "list_id": 0
        }
    },
    {
        "created_at": "Tue Mar 06 07:54:45 +0800 2012",
        "id": 3420489399401432,
        "mid": "3420489399401432",
        "idstr": "3420489399401432",
        "text": "好人",
        "source": "<a href=\"http://m.weibo.com/web/cellphone.php#ipad\" rel=\"nofollow\">iPad客户端</a>",
        "favorited": false,
        "truncated": false,
        "in_reply_to_status_id": "",
        "in_reply_to_user_id": "",
        "in_reply_to_screen_name": "",
        "geo": null,
        "user": {
            "id": 1813080181,
            "idstr": "1813080181",
            "screen_name": "薛蛮子",
            "name": "薛蛮子",
            "province": "11",
            "city": "5",
            "location": "北京 朝阳区",
            "description": "天使投资人薛蛮子 商业计划书请发信箱charlesxuesub@gmail.com",
            "url": "",
            "profile_image_url": "http://tp2.sinaimg.cn/1813080181/50/5615039894/1",
            "profile_url": "charlesxue",
            "domain": "charlesxue",
            "weihao": "",
            "gender": "m",
            "followers_count": 1978491,
            "friends_count": 1469,
            "statuses_count": 36575,
            "favourites_count": 827,
            "created_at": "Mon Sep 06 00:00:00 +0800 2010",
            "following": false,
            "allow_all_act_msg": true,
            "geo_enabled": true,
            "verified": true,
            "verified_type": 0,
            "remark": "",
            "allow_all_comment": true,
            "avatar_large": "http://tp2.sinaimg.cn/1813080181/180/5615039894/1",
            "verified_reason": "天使投资人、微博打拐发起人之一",
            "follow_me": false,
            "online_status": 1,
            "bi_followers_count": 1191,
            "lang": "zh-cn"
        },
        "retweeted_status": {
            "created_at": "Tue Mar 06 07:45:21 +0800 2012",
            "id": 3420487034414220,
            "mid": "3420487034414220",
            "idstr": "3420487034414220",
            "text": "早安！实现宝贵的承诺,已有三子的英国单亲母亲茱莉琼斯Julie Jones,答应挚友病故后领养对方遗下的五名子女,每星期工作40小时,拒领政府救济金,被英国零售业Tesco选为年度慈母!抚养8个孩子对茱莉是沉重的经济负担,但她认为对好友的承诺就该照顾遗孤,她相信换成逝去的挚友,她也会如此！雷锋精神？祝顺利！",
            "source": "<a href=\"http://weibo.com\" rel=\"nofollow\">新浪微博</a>",
            "favorited": false,
            "truncated": false,
            "in_reply_to_status_id": "",
            "in_reply_to_user_id": "",
            "in_reply_to_screen_name": "",
            "thumbnail_pic": "http://ww3.sinaimg.cn/thumbnail/6c096f63jw1dqpqma1fk6j.jpg",
            "bmiddle_pic": "http://ww3.sinaimg.cn/bmiddle/6c096f63jw1dqpqma1fk6j.jpg",
            "original_pic": "http://ww3.sinaimg.cn/large/6c096f63jw1dqpqma1fk6j.jpg",
            "geo": null,
            "user": {
                "id": 1812557667,
                "idstr": "1812557667",
                "screen_name": "莊淑芬Shenan",
                "name": "莊淑芬Shenan",
                "province": "11",
                "city": "1",
                "location": "北京 东城区",
                "description": "热爱好策略，好创意，好品牌，好夥伴的资深广告人",
                "url": "http://blog.sina.com.cn/shenanchuang",
                "profile_image_url": "http://tp4.sinaimg.cn/1812557667/50/5614596887/0",
                "profile_url": "shenanchuang",
                "domain": "shenanchuang",
                "weihao": "",
                "gender": "f",
                "followers_count": 1700715,
                "friends_count": 427,
                "statuses_count": 4132,
                "favourites_count": 33,
                "created_at": "Mon Sep 06 00:00:00 +0800 2010",
                "following": false,
                "allow_all_act_msg": false,
                "geo_enabled": true,
                "verified": true,
                "verified_type": 0,
                "remark": "",
                "allow_all_comment": true,
                "avatar_large": "http://tp4.sinaimg.cn/1812557667/180/5614596887/0",
                "verified_reason": "奥美整合行销传播集团大中华区首席执行长。",
                "follow_me": false,
                "online_status": 1,
                "bi_followers_count": 227,
                "lang": "zh-cn"
            },
            "reposts_count": 850,
            "comments_count": 171,
            "mlevel": 0,
            "visible": {
                "type": 0,
                "list_id": 0
            }
        },
        "reposts_count": 551,
        "comments_count": 190,
        "mlevel": 0,
        "visible": {
            "type": 0,
            "list_id": 0
        }
    },
    {
        "created_at": "Tue Mar 06 07:51:19 +0800 2012",
        "id": 3420488535445238,
        "mid": "3420488535445238",
        "idstr": "3420488535445238",
        "text": "牛",
        "source": "<a href=\"http://m.weibo.com/web/cellphone.php#ipad\" rel=\"nofollow\">iPad客户端</a>",
        "favorited": false,
        "truncated": false,
        "in_reply_to_status_id": "",
        "in_reply_to_user_id": "",
        "in_reply_to_screen_name": "",
        "geo": null,
        "user": {
            "id": 1813080181,
            "idstr": "1813080181",
            "screen_name": "薛蛮子",
            "name": "薛蛮子",
            "province": "11",
            "city": "5",
            "location": "北京 朝阳区",
            "description": "天使投资人薛蛮子 商业计划书请发信箱charlesxuesub@gmail.com",
            "url": "",
            "profile_image_url": "http://tp2.sinaimg.cn/1813080181/50/5615039894/1",
            "profile_url": "charlesxue",
            "domain": "charlesxue",
            "weihao": "",
            "gender": "m",
            "followers_count": 1978491,
            "friends_count": 1469,
            "statuses_count": 36575,
            "favourites_count": 827,
            "created_at": "Mon Sep 06 00:00:00 +0800 2010",
            "following": false,
            "allow_all_act_msg": true,
            "geo_enabled": true,
            "verified": true,
            "verified_type": 0,
            "remark": "",
            "allow_all_comment": true,
            "avatar_large": "http://tp2.sinaimg.cn/1813080181/180/5615039894/1",
            "verified_reason": "天使投资人、微博打拐发起人之一",
            "follow_me": false,
            "online_status": 1,
            "bi_followers_count": 1191,
            "lang": "zh-cn"
        },
        "retweeted_status": {
            "created_at": "Tue Mar 06 07:46:31 +0800 2012",
            "id": 3420487327833397,
            "mid": "3420487327833397",
            "idstr": "3420487327833397",
            "text": "【苹果新一代iPad今年出货量或达4000万台[牛] 】据悉，苹果周三推出的新一代iPad今年的预计出货量将达到4000万台，iPad 2的出货量将在2500万台左右http://t.cn/zOtEK3q三星1月已超越LG Display成为苹果9.7英寸触摸屏幕的最大供应商，1月出货量从去年12月的165万块增加到了245万块（新浪科技）",
            "source": "<a href=\"http://a.weibo.com/proc/productintro.php\" rel=\"nofollow\">新浪微博企业版</a>",
            "favorited": false,
            "truncated": false,
            "in_reply_to_status_id": "",
            "in_reply_to_user_id": "",
            "in_reply_to_screen_name": "",
            "thumbnail_pic": "http://ww1.sinaimg.cn/thumbnail/6593e433jw1dqpqniukrsj.jpg",
            "bmiddle_pic": "http://ww1.sinaimg.cn/bmiddle/6593e433jw1dqpqniukrsj.jpg",
            "original_pic": "http://ww1.sinaimg.cn/large/6593e433jw1dqpqniukrsj.jpg",
            "geo": null,
            "user": {
                "id": 1704191027,
                "idstr": "1704191027",
                "screen_name": "i美股",
                "name": "i美股",
                "province": "11",
                "city": "1000",
                "location": "北京",
                "description": "雪球—全球投资交流平台 <br />\r\nA股、港股、美股，一网打尽 <br />\r\n<br />\r\n索取雪球邀请码，请猛击 <br />\r\nhttp://xueqiu.com/service/apply_inv…",
                "url": "http://www.imeigu.com",
                "profile_image_url": "http://tp4.sinaimg.cn/1704191027/50/1296107920/1",
                "profile_url": "imeigu",
                "domain": "imeigu",
                "weihao": "",
                "gender": "m",
                "followers_count": 119083,
                "friends_count": 95,
                "statuses_count": 19181,
                "favourites_count": 37,
                "created_at": "Wed Mar 03 00:00:00 +0800 2010",
                "following": false,
                "allow_all_act_msg": true,
                "geo_enabled": true,
                "verified": true,
                "verified_type": 2,
                "remark": "",
                "allow_all_comment": true,
                "avatar_large": "http://tp4.sinaimg.cn/1704191027/180/1296107920/1",
                "verified_reason": "雪球财经旗下网站i美股网",
                "follow_me": false,
                "online_status": 1,
                "bi_followers_count": 85,
                "lang": "zh-cn"
            },
            "reposts_count": 168,
            "comments_count": 18,
            "mlevel": 0,
            "visible": {
                "type": 0,
                "list_id": 0
            }
        },
        "reposts_count": 118,
        "comments_count": 36,
        "mlevel": 0,
        "visible": {
            "type": 0,
            "list_id": 0
        }
    },
    {
        "created_at": "Tue Mar 06 07:50:24 +0800 2012",
        "id": 3420488304757516,
        "mid": "3420488304757516",
        "idstr": "3420488304757516",
        "text": "无语 //@查立: 愚民典范。",
        "source": "<a href=\"http://m.weibo.com/web/cellphone.php#ipad\" rel=\"nofollow\">iPad客户端</a>",
        "favorited": false,
        "truncated": false,
        "in_reply_to_status_id": "",
        "in_reply_to_user_id": "",
        "in_reply_to_screen_name": "",
        "geo": null,
        "user": {
            "id": 1813080181,
            "idstr": "1813080181",
            "screen_name": "薛蛮子",
            "name": "薛蛮子",
            "province": "11",
            "city": "5",
            "location": "北京 朝阳区",
            "description": "天使投资人薛蛮子 商业计划书请发信箱charlesxuesub@gmail.com",
            "url": "",
            "profile_image_url": "http://tp2.sinaimg.cn/1813080181/50/5615039894/1",
            "profile_url": "charlesxue",
            "domain": "charlesxue",
            "weihao": "",
            "gender": "m",
            "followers_count": 1978491,
            "friends_count": 1469,
            "statuses_count": 36575,
            "favourites_count": 827,
            "created_at": "Mon Sep 06 00:00:00 +0800 2010",
            "following": false,
            "allow_all_act_msg": true,
            "geo_enabled": true,
            "verified": true,
            "verified_type": 0,
            "remark": "",
            "allow_all_comment": true,
            "avatar_large": "http://tp2.sinaimg.cn/1813080181/180/5615039894/1",
            "verified_reason": "天使投资人、微博打拐发起人之一",
            "follow_me": false,
            "online_status": 1,
            "bi_followers_count": 1191,
            "lang": "zh-cn"
        },
        "retweeted_status": {
            "created_at": "Tue Mar 06 07:36:05 +0800 2012",
            "id": 3420484702268718,
            "mid": "3420484702268718",
            "idstr": "3420484702268718",
            "text": "【申纪兰：网络不是想上就能上 该有人管】这个网,你谁想上就能上？还是要组织批准呢？我有个想法,网也应该有人管,不是谁想弄就能弄,就跟人民日报一样,外国那些人那是瞎弄的,咱不能这样，咱要按照原则去弄，不要好的弄成坏的了，想说什么就说什么,咱是共产党领导下的社会主义国家。http://t.cn/zOtKGR0",
            "source": "<a href=\"http://wbto.cn\" rel=\"nofollow\">享拍微博通</a>",
            "favorited": false,
            "truncated": false,
            "in_reply_to_status_id": "",
            "in_reply_to_user_id": "",
            "in_reply_to_screen_name": "",
            "thumbnail_pic": "http://ww2.sinaimg.cn/thumbnail/62053d21jw1dqpqcp8gs4j.jpg",
            "bmiddle_pic": "http://ww2.sinaimg.cn/bmiddle/62053d21jw1dqpqcp8gs4j.jpg",
            "original_pic": "http://ww2.sinaimg.cn/large/62053d21jw1dqpqcp8gs4j.jpg",
            "geo": null,
            "user": {
                "id": 1644510497,
                "idstr": "1644510497",
                "screen_name": "商界杂志",
                "name": "商界杂志",
                "province": "50",
                "city": "3",
                "location": "重庆 渝中区",
                "description": "全球发行量最大的中文财经期刊之一",
                "url": "http://blog.sina.com.cn/bizshangjie",
                "profile_image_url": "http://tp2.sinaimg.cn/1644510497/50/5623156391/1",
                "profile_url": "shjie",
                "domain": "shjie",
                "weihao": "",
                "gender": "m",
                "followers_count": 141237,
                "friends_count": 1064,
                "statuses_count": 10288,
                "favourites_count": 4,
                "created_at": "Wed Sep 02 00:00:00 +0800 2009",
                "following": false,
                "allow_all_act_msg": true,
                "geo_enabled": true,
                "verified": true,
                "verified_type": 3,
                "remark": "",
                "allow_all_comment": true,
                "avatar_large": "http://tp2.sinaimg.cn/1644510497/180/5623156391/1",
                "verified_reason": "商界杂志官方微博",
                "follow_me": false,
                "online_status": 1,
                "bi_followers_count": 401,
                "lang": "zh-cn"
            },
            "reposts_count": 4487,
            "comments_count": 1026,
            "mlevel": 0,
            "visible": {
                "type": 0,
                "list_id": 0
            }
        },
        "reposts_count": 1833,
        "comments_count": 941,
        "mlevel": 0,
        "visible": {
            "type": 0,
            "list_id": 0
        }
    },
    {
        "created_at": "Tue Mar 06 07:49:01 +0800 2012",
        "id": 3420487956554721,
        "mid": "3420487956554721",
        "idstr": "3420487956554721",
        "text": "转发微博",
        "source": "<a href=\"http://m.weibo.com/web/cellphone.php#ipad\" rel=\"nofollow\">iPad客户端</a>",
        "favorited": false,
        "truncated": false,
        "in_reply_to_status_id": "",
        "in_reply_to_user_id": "",
        "in_reply_to_screen_name": "",
        "geo": null,
        "user": {
            "id": 1813080181,
            "idstr": "1813080181",
            "screen_name": "薛蛮子",
            "name": "薛蛮子",
            "province": "11",
            "city": "5",
            "location": "北京 朝阳区",
            "description": "天使投资人薛蛮子 商业计划书请发信箱charlesxuesub@gmail.com",
            "url": "",
            "profile_image_url": "http://tp2.sinaimg.cn/1813080181/50/5615039894/1",
            "profile_url": "charlesxue",
            "domain": "charlesxue",
            "weihao": "",
            "gender": "m",
            "followers_count": 1978491,
            "friends_count": 1469,
            "statuses_count": 36575,
            "favourites_count": 827,
            "created_at": "Mon Sep 06 00:00:00 +0800 2010",
            "following": false,
            "allow_all_act_msg": true,
            "geo_enabled": true,
            "verified": true,
            "verified_type": 0,
            "remark": "",
            "allow_all_comment": true,
            "avatar_large": "http://tp2.sinaimg.cn/1813080181/180/5615039894/1",
            "verified_reason": "天使投资人、微博打拐发起人之一",
            "follow_me": false,
            "online_status": 1,
            "bi_followers_count": 1191,
            "lang": "zh-cn"
        },
        "retweeted_status": {
            "created_at": "Tue Mar 06 07:48:07 +0800 2012",
            "id": 3420487730720385,
            "mid": "3420487730720385",
            "idstr": "3420487730720385",
            "text": "分享图片：来自山东的全国政协委员宗立成接受采访时表示：高官送子女出国读书是公民权利，没什么可非议，不应戴有色眼镜看待干部子女。——点评：官员公示财产，供公民随时查询，子女送哪里留学，都随你便！",
            "source": "<a href=\"http://weibo.com\" rel=\"nofollow\">新浪微博</a>",
            "favorited": false,
            "truncated": false,
            "in_reply_to_status_id": "",
            "in_reply_to_user_id": "",
            "in_reply_to_screen_name": "",
            "thumbnail_pic": "http://ww3.sinaimg.cn/thumbnail/5a0f7965jw1dqpqmc1v7uj.jpg",
            "bmiddle_pic": "http://ww3.sinaimg.cn/bmiddle/5a0f7965jw1dqpqmc1v7uj.jpg",
            "original_pic": "http://ww3.sinaimg.cn/large/5a0f7965jw1dqpqmc1v7uj.jpg",
            "geo": null,
            "user": {
                "id": 1510963557,
                "idstr": "1510963557",
                "screen_name": "肖雪慧",
                "name": "肖雪慧",
                "province": "51",
                "city": "1",
                "location": "四川 成都",
                "description": "",
                "url": "http://blog.sina.com.cn/xiaoxuehuiblog",
                "profile_image_url": "http://tp2.sinaimg.cn/1510963557/50/1279879445/0",
                "profile_url": "u/1510963557",
                "domain": "",
                "weihao": "",
                "gender": "f",
                "followers_count": 29865,
                "friends_count": 1968,
                "statuses_count": 14202,
                "favourites_count": 730,
                "created_at": "Tue Dec 22 00:00:00 +0800 2009",
                "following": false,
                "allow_all_act_msg": false,
                "geo_enabled": true,
                "verified": true,
                "verified_type": 0,
                "remark": "",
                "allow_all_comment": true,
                "avatar_large": "http://tp2.sinaimg.cn/1510963557/180/1279879445/0",
                "verified_reason": "西南民族大学教授肖雪慧",
                "follow_me": false,
                "online_status": 1,
                "bi_followers_count": 1913,
                "lang": "zh-cn"
            },
            "reposts_count": 3159,
            "comments_count": 641,
            "mlevel": 0,
            "visible": {
                "type": 0,
                "list_id": 0
            }
        },
        "reposts_count": 1029,
        "comments_count": 319,
        "mlevel": 0,
        "visible": {
            "type": 0,
            "list_id": 0
        }
    },
    {
        "created_at": "Tue Mar 06 07:48:42 +0800 2012",
        "id": 3420487876862610,
        "mid": "3420487876862610",
        "idstr": "3420487876862610",
        "text": "转发微博",
        "source": "<a href=\"http://m.weibo.com/web/cellphone.php#ipad\" rel=\"nofollow\">iPad客户端</a>",
        "favorited": false,
        "truncated": false,
        "in_reply_to_status_id": "",
        "in_reply_to_user_id": "",
        "in_reply_to_screen_name": "",
        "geo": null,
        "user": {
            "id": 1813080181,
            "idstr": "1813080181",
            "screen_name": "薛蛮子",
            "name": "薛蛮子",
            "province": "11",
            "city": "5",
            "location": "北京 朝阳区",
            "description": "天使投资人薛蛮子 商业计划书请发信箱charlesxuesub@gmail.com",
            "url": "",
            "profile_image_url": "http://tp2.sinaimg.cn/1813080181/50/5615039894/1",
            "profile_url": "charlesxue",
            "domain": "charlesxue",
            "weihao": "",
            "gender": "m",
            "followers_count": 1978491,
            "friends_count": 1469,
            "statuses_count": 36575,
            "favourites_count": 827,
            "created_at": "Mon Sep 06 00:00:00 +0800 2010",
            "following": false,
            "allow_all_act_msg": true,
            "geo_enabled": true,
            "verified": true,
            "verified_type": 0,
            "remark": "",
            "allow_all_comment": true,
            "avatar_large": "http://tp2.sinaimg.cn/1813080181/180/5615039894/1",
            "verified_reason": "天使投资人、微博打拐发起人之一",
            "follow_me": false,
            "online_status": 1,
            "bi_followers_count": 1191,
            "lang": "zh-cn"
        },
        "retweeted_status": {
            "created_at": "Tue Mar 06 06:07:02 +0800 2012",
            "id": 3420462292223722,
            "mid": "3420462292223722",
            "idstr": "3420462292223722",
            "text": "有位禅师有一个爱抱怨的弟子。一天，禅师将一把盐放入一杯水中让弟子喝，弟子说：咸得发苦。禅师又把更多的盐撒进湖里，让弟子再尝湖水。弟子喝后说：纯净甜美。禅师说：生命中的痛苦是盐，它的咸淡取决于盛它的容器。你愿做一杯水，还是一片湖水？",
            "source": "<a href=\"http://weibo.pp.cc/time/\" rel=\"nofollow\">皮皮时光机</a>",
            "favorited": false,
            "truncated": false,
            "in_reply_to_status_id": "",
            "in_reply_to_user_id": "",
            "in_reply_to_screen_name": "",
            "thumbnail_pic": "http://ww4.sinaimg.cn/thumbnail/83909b47jw1dqpns202y2j.jpg",
            "bmiddle_pic": "http://ww4.sinaimg.cn/bmiddle/83909b47jw1dqpns202y2j.jpg",
            "original_pic": "http://ww4.sinaimg.cn/large/83909b47jw1dqpns202y2j.jpg",
            "geo": null,
            "user": {
                "id": 2207292231,
                "idstr": "2207292231",
                "screen_name": "实用微招聘",
                "name": "实用微招聘",
                "province": "400",
                "city": "1",
                "location": "海外 美国",
                "description": "特别关注，关注特别！发布全球人生最特别的事，您的关注是我前进的动力！",
                "url": "http://weibo.com/2207292231",
                "profile_image_url": "http://tp4.sinaimg.cn/2207292231/50/5624752492/0",
                "profile_url": "51770880",
                "domain": "mingrenhuicui",
                "weihao": "51770880",
                "gender": "f",
                "followers_count": 187922,
                "friends_count": 69,
                "statuses_count": 5017,
                "favourites_count": 1,
                "created_at": "Wed Jun 29 00:00:00 +0800 2011",
                "following": false,
                "allow_all_act_msg": true,
                "geo_enabled": true,
                "verified": false,
                "verified_type": -1,
                "remark": "",
                "allow_all_comment": true,
                "avatar_large": "http://tp4.sinaimg.cn/2207292231/180/5624752492/0",
                "verified_reason": "",
                "follow_me": false,
                "online_status": 1,
                "bi_followers_count": 9,
                "lang": "zh-cn"
            },
            "reposts_count": 1448,
            "comments_count": 118,
            "mlevel": 0,
            "visible": {
                "type": 0,
                "list_id": 0
            }
        },
        "reposts_count": 1091,
        "comments_count": 142,
        "mlevel": 0,
        "visible": {
            "type": 0,
            "list_id": 0
        }
    },
    {
        "created_at": "Tue Mar 06 07:39:54 +0800 2012",
        "id": 3420485662569912,
        "mid": "3420485662569912",
        "idstr": "3420485662569912",
        "text": "#纪念朱光潜先生#我把我的信条叫做“三此主义”，就是此身、此时、此地。一、此身应该做而且能够做的事，就得由此身担当起，不推诿给旁人。二、此时应该做而且能够做的事，就得在此时做，不拖延到未来。三、此地（我的地位、环境）应该做而且能够做的事，就得在此地做，不推诿到想象中的另一地位去做。",
        "source": "<a href=\"http://m.weibo.com/web/cellphone.php#ipad\" rel=\"nofollow\">iPad客户端</a>",
        "favorited": false,
        "truncated": false,
        "in_reply_to_status_id": "",
        "in_reply_to_user_id": "",
        "in_reply_to_screen_name": "",
        "thumbnail_pic": "http://ww2.sinaimg.cn/thumbnail/6c116875jw1dqpqgoat1tj.jpg",
        "bmiddle_pic": "http://ww2.sinaimg.cn/bmiddle/6c116875jw1dqpqgoat1tj.jpg",
        "original_pic": "http://ww2.sinaimg.cn/large/6c116875jw1dqpqgoat1tj.jpg",
        "geo": null,
        "user": {
            "id": 1813080181,
            "idstr": "1813080181",
            "screen_name": "薛蛮子",
            "name": "薛蛮子",
            "province": "11",
            "city": "5",
            "location": "北京 朝阳区",
            "description": "天使投资人薛蛮子 商业计划书请发信箱charlesxuesub@gmail.com",
            "url": "",
            "profile_image_url": "http://tp2.sinaimg.cn/1813080181/50/5615039894/1",
            "profile_url": "charlesxue",
            "domain": "charlesxue",
            "weihao": "",
            "gender": "m",
            "followers_count": 1978491,
            "friends_count": 1469,
            "statuses_count": 36575,
            "favourites_count": 827,
            "created_at": "Mon Sep 06 00:00:00 +0800 2010",
            "following": false,
            "allow_all_act_msg": true,
            "geo_enabled": true,
            "verified": true,
            "verified_type": 0,
            "remark": "",
            "allow_all_comment": true,
            "avatar_large": "http://tp2.sinaimg.cn/1813080181/180/5615039894/1",
            "verified_reason": "天使投资人、微博打拐发起人之一",
            "follow_me": false,
            "online_status": 1,
            "bi_followers_count": 1191,
            "lang": "zh-cn"
        },
        "reposts_count": 954,
        "comments_count": 188,
        "mlevel": 0,
        "visible": {
            "type": 0,
            "list_id": 0
        }
    },
    {
        "created_at": "Tue Mar 06 07:34:05 +0800 2012",
        "id": 3420484198444804,
        "mid": "3420484198444804",
        "idstr": "3420484198444804",
        "text": "一诺千金！这种人今天有木有？",
        "source": "<a href=\"http://m.weibo.com/web/cellphone.php#ipad\" rel=\"nofollow\">iPad客户端</a>",
        "favorited": false,
        "truncated": false,
        "in_reply_to_status_id": "",
        "in_reply_to_user_id": "",
        "in_reply_to_screen_name": "",
        "geo": null,
        "user": {
            "id": 1813080181,
            "idstr": "1813080181",
            "screen_name": "薛蛮子",
            "name": "薛蛮子",
            "province": "11",
            "city": "5",
            "location": "北京 朝阳区",
            "description": "天使投资人薛蛮子 商业计划书请发信箱charlesxuesub@gmail.com",
            "url": "",
            "profile_image_url": "http://tp2.sinaimg.cn/1813080181/50/5615039894/1",
            "profile_url": "charlesxue",
            "domain": "charlesxue",
            "weihao": "",
            "gender": "m",
            "followers_count": 1978491,
            "friends_count": 1469,
            "statuses_count": 36575,
            "favourites_count": 827,
            "created_at": "Mon Sep 06 00:00:00 +0800 2010",
            "following": false,
            "allow_all_act_msg": true,
            "geo_enabled": true,
            "verified": true,
            "verified_type": 0,
            "remark": "",
            "allow_all_comment": true,
            "avatar_large": "http://tp2.sinaimg.cn/1813080181/180/5615039894/1",
            "verified_reason": "天使投资人、微博打拐发起人之一",
            "follow_me": false,
            "online_status": 1,
            "bi_followers_count": 1191,
            "lang": "zh-cn"
        },
        "retweeted_status": {
            "created_at": "Mon Mar 05 20:49:08 +0800 2012",
            "id": 3420321887759709,
            "mid": "3420321887759709",
            "idstr": "3420321887759709",
            "text": "什么么叫承诺？欧兴田，86岁，享受师级待遇，放弃天伦之乐，忍着伤病奔走30年,以一己之力花费100多万，没花财政一分钱，硬修起一座2400多名烈士的抗日烈士陵园.有人说他傻，但他只为60年前的承诺。“当年参加革命...大家在破教室里发誓，谁活,谁就要为牺牲战友守墓。既然我答应了，就得做到。 ",
            "source": "<a href=\"http://weibo.pp.cc/time/\" rel=\"nofollow\">皮皮时光机</a>",
            "favorited": false,
            "truncated": false,
            "in_reply_to_status_id": "",
            "in_reply_to_user_id": "",
            "in_reply_to_screen_name": "",
            "thumbnail_pic": "http://ww1.sinaimg.cn/thumbnail/4fd03e93jw1dqp7njk3c5j.jpg",
            "bmiddle_pic": "http://ww1.sinaimg.cn/bmiddle/4fd03e93jw1dqp7njk3c5j.jpg",
            "original_pic": "http://ww1.sinaimg.cn/large/4fd03e93jw1dqp7njk3c5j.jpg",
            "geo": null,
            "user": {
                "id": 1339047571,
                "idstr": "1339047571",
                "screen_name": "历史解密网",
                "name": "历史解密网",
                "province": "21",
                "city": "3",
                "location": "辽宁 鞍山",
                "description": "解密历史事件，还原历史真相，请关注@历史解密网 。投稿或合作请私信。",
                "url": "http://www.history8.com",
                "profile_image_url": "http://tp4.sinaimg.cn/1339047571/50/5601440651/1",
                "profile_url": "u/1339047571",
                "domain": "",
                "weihao": "",
                "gender": "m",
                "followers_count": 47873,
                "friends_count": 663,
                "statuses_count": 3250,
                "favourites_count": 13,
                "created_at": "Wed Jan 19 00:00:00 +0800 2011",
                "following": false,
                "allow_all_act_msg": true,
                "geo_enabled": false,
                "verified": false,
                "verified_type": -1,
                "remark": "",
                "allow_all_comment": true,
                "avatar_large": "http://tp4.sinaimg.cn/1339047571/180/5601440651/1",
                "verified_reason": "",
                "follow_me": false,
                "online_status": 1,
                "bi_followers_count": 432,
                "lang": "zh-cn"
            },
            "reposts_count": 3377,
            "comments_count": 501,
            "mlevel": 0,
            "visible": {
                "type": 0,
                "list_id": 0
            }
        },
        "reposts_count": 1449,
        "comments_count": 451,
        "mlevel": 0,
        "visible": {
            "type": 0,
            "list_id": 0
        }
    }],
    "hasvisible": false,
    "previous_cursor": 0,
    "next_cursor": 0,
    "total_number": 36538
}